# clear the environment
rm(list = ls())

# refresh the moe school directory list
# download the moe zip file into the tempdir() generated by R
download.file(
    "https://data.gov.sg/dataset/c004b703-5e64-47db-a504-e60e74fd3b32/download",
    paste0(tempdir(), "/moe.zip"),
)
# unzip the downloaded zip
unzip(
    paste0(tempdir(), "/moe.zip"),
    exdir = paste0(tempdir(), "/moe"),
)
# copy the file general-information-of-schools into the data folder
file.copy(
    from = paste0(tempdir(), "/moe/general-information-of-schools.csv"),
    to = "data/originals/moe-school-directory.csv",
    overwrite = T
)

# refresh the lta station info
# download the csv file directly into the data folder
download.file(
    "https://datamall.lta.gov.sg/content/dam/datamall/datasets/PublicTransportRelated/Train_Station_Codes_and_Chinese_Names.zip",
    paste0(tempdir(), "/lta.zip")
)
# unzip the downloaded zip
unzip(
    paste0(tempdir(), "/lta.zip"),
    exdir = paste0(tempdir(), "/lta")
)
# copy the file into the data folder
file.copy(
    from = list.files(paste0(tempdir(), "/lta/"), full.names = T)[1],
    to = "data/originals/lta-station-info.csv",
    overwrite = T
)